# Generated by Django 4.2.4 on 2023-09-09 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos')),
                ('nome', models.CharField(max_length=250)),
                ('idade', models.IntegerField()),
                ('cpf', models.CharField(max_length=11)),
                ('cep', models.CharField(max_length=8)),
                ('cidade', models.CharField(max_length=300)),
                ('bairro', models.CharField(max_length=300)),
                ('rua', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('telefone', models.CharField(max_length=11)),
            ],
        ),
    ]
